# Configuration commune pour les types MIME
include mime.types;
types {
    application/javascript mjs;
    application/wasm wasm;
}

# Redirect all HTTP to HTTPS
server {
    listen 80;
    server_name *.localhost;
    return 301 https://$host$request_uri;
}

# Configuration Portainer - Domaine public uniquement

# Redirection HTTP vers HTTPS pour le domaine public
server {
    listen 80;
    server_name portainer.example.com;
    return 301 https://$host$request_uri;
}


# Kuma HTTPS
server {
    listen 443 ssl http2;
    server_name kuma.example.com;

    ssl_certificate /etc/nginx/certificates/serveur.pem;
    ssl_certificate_key /etc/nginx/certificates/serveur-key.pem;

    include /etc/nginx/conf.d/ssl_common.inc;
    add_header X-Frame-Options "DENY" always;

        # Endpoint interne Authelia (copier dans chaque config)
    location /authelia {
        internal;
        set $upstream_authelia http://authelia:9091/api/verify;
        proxy_pass $upstream_authelia;

        proxy_set_header Host $host;
        proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Uri $request_uri;
        proxy_set_header X-Forwarded-For $remote_addr;

        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
    }

    location / {
    
        # Vérifie avec Authelia
        auth_request /authelia;

        # Variables user
        auth_request_set $user $upstream_http_remote_user;
        auth_request_set $groups $upstream_http_remote_groups;

        # Redirige vers login si pas authentifié
        error_page 401 =302 https://authelia.example.com/?rd=$scheme://$http_host$request_uri;

        proxy_pass http://kuma:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

# Kuma local HTTP
server {
    listen 80;
    server_name kuma.localhost _;

    location / {
        proxy_pass http://kuma:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}


# Pgadmin local HTTP
server {
    listen 80;
    server_name pgadmin.localhost _;

    location / {
        proxy_pass http://pgadmin:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
    }
}







