---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /
- openweathermap:
    label: Your City #optional
    latitude: 0.0000
    longitude: 0.0000
    units: metric
    provider: openweathermap
    apiKey: your_openweathermap_api_key
    cache: 300
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- datetime:
    locale: en
    text_size: x1
    format:
      timeStyle: long
